### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by toqueteos** [toqueteos/merge-playground#1]
# Implementing `git merge` for go-git

## Roadmap

- [x] Create a _playground_ repo to play with.
- [ ] Basic merge functionality
    - [ ] Compare two branches

## Problems

- As of now, `go-git` can't open local repositories. We need to create a new one and pull it from the remote.
- There are plenty of merge strategies, in order to do something useful today I'll focus on just one

## Merge strategies

- **Resolve**: A two headed merge strategy using a 3-way merge algorithm. This is used by default in Git.
- **Recursive**: A two headed merge strategy using a 3-way merge algorithm. This algorithm looks at situations where multiple common ancestors are eligible and creates a merged tree of the common ancestors to be used as a reference. Usually, this method has less conflicts and carries with it multiple sub-options.
- **Octopus**: This merge strategy can merge in multiple heads. When trying to pull multiple topic branches into a single merge, an octopus is the default method that Git will use.
- **Ours**: Another multiple head strategy, which simply ignores all changes from the other branches. At first it may sound like a useless idea, but it could be used to keep the history of a branch without actually keeping the branch itself.
- **Subtree**: A much more advanced merge strategy based on the recursive which trees are adjusted to result in a better merge.

**Comment by toqueteos** [comment]
Unfortunately as shown in https://github.com/src-d/go-git/issues/4 the commit iteration process is subject to changes so may find some obstacles along the way to completing this.

**Comment by toqueteos** [comment]
Ok, first step done. I can see the contents of each branch.

Unfortunately, branch switching (something like the checkout command) is not supported right now so I have multiple copies of the repository on memory.

```
Found branch: refs/heads/a
ls-tree 32333863616266303439393966663261346539613363316435653334353531666138656536363661
LICENSE
README.md
main.go
ls-tree 39633564613863353838303836333863613135356438623665366664613935643963323235376639
LICENSE
README.md
Found branch: refs/heads/a2
ls-tree 32333863616266303439393966663261346539613363316435653334353531666138656536363661
LICENSE
README.md
main.go
ls-tree 39633564613863353838303836333863613135356438623665366664613935643963323235376639
LICENSE
README.md
ls-tree 64616237316362336261346161663762653237353763386637353565353337363363316636636438
LICENSE
README.md
main.go
Found branch: refs/heads/b
ls-tree 62326566653331666239363263656365333733653135326438343136306165633863386463616635
LICENSE
README.md
main.go
ls-tree 32333863616266303439393966663261346539613363316435653334353531666138656536363661
LICENSE
README.md
main.go
ls-tree 39633564613863353838303836333863613135356438623665366664613935643963323235376639
LICENSE
README.md
Found branch: refs/heads/master
ls-tree 39633564613863353838303836333863613135356438623665366664613935643963323235376639
LICENSE
README.md
```

**Comment by toqueteos** [comment]
Almost reached goal. It's now puzzling me so I'll probably finish it by this night
